#!/bin/bash

INPUTFILE="INPUTFILE ../../../SimulationResults/Builder/Rising/LifetimePaper/112Sn/"
FILEEXT1="150mev"
FILEEXT2="fs.root"
OUTPUTFILE="OUTPUTFILE ../../../SimulationResults/Reconstructor/Rising/LifetimePaper/112Sn/"
SPECTRABINANDRANGE="SPECTRABINANDRANGE 1000 0. 2000."
BETADOPPLERAVERAGE="BETADOPPLERAVERAGE "
BETATOFAVERAGE="BETATOFAVERAGE  0.5081"
BETAAFTERTARGETAVERAGE="BETAAFTERTARGETAVERAGE 0.459"
DECAYPOSITIONZ="DECAYPOSITIONZ 0.0"
CLUSTERINCLUDE="CLUSTERINCLUDE 1"
MINIBALLINCLUDE="MINIBALLINCLUDE 1"
CLUSTERFIFIND="CLUSTERFIFIND "
MINIBALLFIFIND="MINIBALLFIFIND "
HECTORINCLUDE="HECTORINCLUDE 1"
STATISTICSREDUCTIONFACTOR="STATISTICSREDUCTIONFACTOR 1"
END="END"
FILE="./input/RisingReconstructor.in"
#Beta=("0.4778" "0.4732" "0.4683");
Beta=("0.485" "0.4759" "0.4711" "0.4682" "0.4665");
a=0
#for arg1 in 185 370 740 
for arg1 in 0 250 500  750 999
do
    BETA=${Beta[$a]}

    for arg2 in 1  2  
    do   
        echo ""$INPUTFILE$FILEEXT1$arg1$FILEEXT2"
"$OUTPUTFILE$FILEEXT1$arg1$FILEEXT2"
"$CLUSTERINCLUDE"
"$MINIBALLINCLUDE"
"$HECTORINCLUDE"
"$MINIBALLFIFIND$arg2"
"$CLUSTERFIFIND$arg2"
"$SPECTRABINANDRANGE"
"$BETADOPPLERAVERAGE$BETA"
"$BETATOFAVERAGE"
"$BETAAFTERTARGETAVERAGE"
"$DECAYPOSITIONZ"
"$STATISTICSREDUCTIONFACTOR"
"$END" 
" > $FILE
        
        time ./RisingReconstructor
    done
    let a=$a+1    
done

exit 0
