#!/bin/bash

INPUTFILE="INPUTFILE ../../../SimulationResults/Builder/Rising/LifetimePaper/500keV/"
FILEEXT1="100mev_500kev_"
FILEEXT2="ps.root"
OUTPUTFILE="OUTPUTFILE ../../../SimulationResults/Reconstructor/Rising/LifetimePaper/500keV/"
SPECTRABINANDRANGE="SPECTRABINANDRANGE 1000 0. 1000."
BETADOPPLERAVERAGE="BETADOPPLERAVERAGE 0.4295"
BETATOFAVERAGE="BETATOFAVERAGE  0.4295"
DECAYPOSITIONZ="DECAYPOSITIONZ "
CLUSTERINCLUDE="CLUSTERINCLUDE 1"
MINIBALLINCLUDE="MINIBALLINCLUDE 1"
CLUSTERFIFIND="CLUSTERFIFIND "
MINIBALLFIFIND="MINIBALLFIFIND "
HECTORINCLUDE="HECTORINCLUDE 1"
END="END"
FILE="./input/RisingReconstructor.in"

POSITIONZ1=("0.0" "1.0" "2.0");
a=0
for arg1 in 0 50 100 
do
    positionz=${POSITIONZ1[$a]}

    for arg2 in 1  2  
    do   
        echo ""$INPUTFILE$FILEEXT1$arg1$FILEEXT2"
"$OUTPUTFILE$FILEEXT1$arg1$FILEEXT2"
"$CLUSTERINCLUDE"
"$MINIBALLINCLUDE"
"$HECTORINCLUDE"
"$MINIBALLFIFIND$arg2"
"$CLUSTERFIFIND$arg2"
"$SPECTRABINANDRANGE"
"$BETADOPPLERAVERAGE"
"$BETATOFAVERAGE"
"$DECAYPOSITIONZ$positionz"
"$END" 
" > $FILE
        
        time ./RisingReconstructor
    done
    let a=$a+1    
done

exit 0
