#!/bin/bash

BEAMISOTOPE="BEAMISOTOPE 37 20 20"
BEAMENERGY="BEAMENERGY 196.72 6.063"
BEAMPOSITION="BEAMPOSITION 0.0 2.35 0.0 2.16"
BEAMANGLE="BEAMANGLE 0.0 0.658 0.0 360.0"
TARGET="TARGET 2 7.0 7.0 700"
TARGETANGULARBROADENING="TARGETANGULARBROADENING 1 1.563"
MASSCHANGE="MASSCHANGE 1 1"
BORREL="BORREL 1 8."
GOLDHABER="GOLDHABER 1 90."
GAMMAINPUT="GAMMAINPUT ./input/36K.in"
THETARANGE="THETARANGE 0.0 180.0"
NUMBEROFEVENTS="NUMBEROFEVENTS 1000000"
DEFAULTCUTVALUE="DEFAULTCUTVALUE 0.01"
OUTPUTFILE1="OUTPUTFILE ../SimulationResults/Generator/36kPaper/36K"
OUTPUTFILE1B="keV"
OUTPUTFILE2="psHigherEnergy.root"
DEDXTABLE="DEDXTABLE 1 ./dEdXTables/CaOnBe.in ./dEdXTables/KOnBe.in"
END="END"


FILE="./input/EventGenerator.in"
FILE2="./input/36K.in"
LIMIT1=816
LIMIT2=11

rm ./input/EventGenerator.in

for ((arg1=808; arg1 <= LIMIT1;arg1=arg1+1))
do
for ((arg2=4; arg2 <= LIMIT2;arg2=arg2+1))
do


echo "LEVEL 0   0.    0.  0.
LEVEL 1 100. $arg1 $arg2
DECAY 1 0 100.
END
" > $FILE2

echo ""$BEAMISOTOPE"
"$BEAMENERGY"
"$BEAMPOSITION"
"$BEAMANGLE"
"$TARGET"
"$TARGETANGULARBROADENING"
"$MASSCHANGE"
"$BORREL"
"$GOLDHABER"
"$GAMMAINPUT"
"$THETARANGE"
"$NUMBEROFEVENTS"
"$DEFAULTCUTVALUE"
"$OUTPUTFILE1$arg1$OUTPUTFILE1B$arg2$OUTPUTFILE2"
"$DEDXTABLE"
"$END" 
" > $FILE

time EventGenerator run_nothing.mac
done
done
exit 0
