#ifndef Globals_h
#define Globals_h

//FOR RISING:
#define NUMBEROFCLUSTERDETECTORS 12
#define NUMBEROFMINIBALLDETECTORS 8
#define NUMBEROFHECTORDETECTORS 8

// For the RIBF
#define NUMBEROFSHOGUNCRYSTALS 514
#define NUMBEROFSHOGUNADDBACKCRYSTALS 514
#define NUMBEROFDALI2CRYSTALS 186
#define NUMBEROFDALI2ADDBACKCRYSTALS 186
#define NUMBEROFLABR3ARRAYCRYSTALS 8 
#define NUMBEROFGRAPEDETECTORS 18
#define NUMBEROFSGTDETECTORS 10 

#endif
