#!/bin/bash
cd input
ln -sf EventBuilder.in.dummy EventBuilder.in
#cd ../geometry
#ln -sf configurations/case$1_in.txt Shogun_geometry_in.txt
cd ..

INPUTFILE="INPUTFILE ../SimulationResults/Generator/Efficiency/"
FILEEXT0="_"
FILEEXT1="mev"
FILEEXT2="kev.root"
FILEEXT3="kev_gagg_conf11_with_65mu_tape.root"
OUTPUTFILE="OUTPUTFILE ../SimulationResults/Builder/Shogun/"
SHOGUNINCLUDE="SHOGUNINCLUDE 1"
SHOGUNFIINCLUDE="SHOGUNFIINCLUDE 1"
SHOGUNENERGYRESOLUTION="SHOGUNENERGYRESOLUTION 2 1.8 0.5"
SHOGUNTIMERESOLUTION="SHOGUNTIMERESOLUTION 0.5 0"
SHOGUNHOUSINGTHICKNESSXYZ="SHOGUNHOUSINGTHICKNESSXYZ 0 0.1 0.1 0.1"
SHOGUNMGOTHICKNESSXYZ="SHOGUNMGOTHICKNESSXYZ 1 0.0065 0.0065 0.0065"
POSDETECTORONTARGETRESOLUTION="POSDETECTORONTARGETRESOLUTION .3"
ENERGYDETECTORAFTERTARGETINCLUDE="ENERGYDETECTORAFTERTARGETINCLUDE 0"
POSDETECTORAFTERTARGETDISTANCE="POSDETECTORAFTERTARGETDISTANCE 100."
POSDETECTORAFTERTARGETRESOLUTION="POSDETECTORAFTERTARGETRESOLUTION .3"
BETARESOLUTION="BETARESOLUTION 0.001"
BEAMPIPEINCLUDE="BEAMPIPEINCLUDE 0"
TARGETHOLDERINCLUDE="TARGETHOLDERINCLUDE 0"
END="END"

FILE="./input/EventBuilder.in"

for arg1 in 100 200
do
for arg2 in 250 500 1000 2000 5000 10000
do

echo ""$INPUTFILE$arg1$FILEEXT1$arg2$FILEEXT2"
"$OUTPUTFILE$arg1$FILEEXT1$arg2$FILEEXT3"
"$SHOGUNINCLUDE"
"$SHOGUNFIINCLUDE"
"$SHOGUNENERGYRESOLUTION"
"$SHOGUNTIMERESOLUTION"
"$SHOGUNHOUSINGTHICKNESSXYZ"
"$SHOGUNMGOTHICKNESSXYZ"
"$POSDETECTORONTARGETRESOLUTION"
"$ENERGYDETECTORAFTERTARGETINCLUDE"
"$POSDETECTORAFTERTARGETDISTANCE"
"$POSDETECTORAFTERTARGETRESOLUTION"
"$BETARESOLUTION"
"$BEAMPIPEINCLUDE"
"$TARGETHOLDERINCLUDE"
"$END" 
" > $FILE

time EventBuilder run_nothing.mac
done
done

exit 0
