#!/bin/bash
INPUTFILE="INPUTFILE ../SimulationResults/Generator/112sn/112sn112sn180mev"
FILEEXT0="mg"
FILEEXT1="fs.root"
FILEEXT2="_112sn112sn180mev"
OUTPUTFILE="OUTPUTFILE ../SimulationResults/Builder/Shogun/112sn/Case"
SHOGUNINCLUDE="SHOGUNINCLUDE 1"
SHOGUNENERGYRESOLUTION="SHOGUNENERGYRESOLUTION 2 0.771 0.5"
SHOGUNTIMERESOLUTION="SHOGUNTIMERESOLUTION 0.5 0"
SHOGUNHOUSINGTHICKNESSXYZ="SHOGUNHOUSINGTHICKNESSXYZ 1 0.1 0.1 0.1"
SHOGUNMGOTHICKNESSXYZ="SHOGUNMGOTHICKNESSXYZ 1 0.1 0.1 0.1"
POSDETECTORONTARGETRESOLUTION="POSDETECTORONTARGETRESOLUTION .3"
ENERGYDETECTORAFTERTARGETINCLUDE="ENERGYDETECTORAFTERTARGETINCLUDE 0"
POSDETECTORAFTERTARGETDISTANCE="POSDETECTORAFTERTARGETDISTANCE 100."
POSDETECTORAFTERTARGETRESOLUTION="POSDETECTORAFTERTARGETRESOLUTION .3"
BETARESOLUTION="BETARESOLUTION 0.001"
BEAMPIPEINCLUDE="BEAMPIPEINCLUDE 0"
TARGETHOLDERINCLUDE="TARGETHOLDERINCLUDE 0"
END="END"

FILE="./input/EventBuilder.in"


for arg1 in  1 100 200 300 400 500 600 700 800 900 999
do
for arg2 in 0 100 200 300 400 500 600 700 800 900 999
do

echo ""$INPUTFILE$arg1$FILEEXT0$arg2$FILEEXT1"
"$OUTPUTFILE$1$FILEEXT2$arg1$FILEEXT0$arg2$FILEEXT1"
"$SHOGUNINCLUDE"
"$SHOGUNENERGYRESOLUTION"
"$SHOGUNTIMERESOLUTION"
"$SHOGUNHOUSINGTHICKNESSXYZ"
"$SHOGUNMGOTHICKNESSXYZ"
"$POSDETECTORONTARGETRESOLUTION"
"$ENERGYDETECTORAFTERTARGETINCLUDE"
"$POSDETECTORAFTERTARGETDISTANCE"
"$POSDETECTORAFTERTARGETRESOLUTION"
"$BETARESOLUTION"
"$BEAMPIPEINCLUDE"
"$TARGETHOLDERINCLUDE"
"$END" 
" > $FILE

time EventBuilder run_nothing.mac
done
done

exit 0
