#!/bin/bash
INPUTFILE="INPUTFILE ../SimulationResults/Generator/Efficiency/"
FILEEXT1="keV.root"
OUTPUTFILE="OUTPUTFILE ../SimulationResults/Builder/Shogun/Efficiency/Case"
FILEEXT2="_"
FILEEXT3="keVStopped.root"
SHOGUNINCLUDE="SHOGUNINCLUDE 1"
SHOGUNENERGYRESOLUTION="SHOGUNENERGYRESOLUTION 2 0.77 0.5"
SHOGUNTIMERESOLUTION="SHOGUNTIMERESOLUTION 0.5 0"
SHOGUNHOUSINGTHICKNESSXYZ="SHOGUNHOUSINGTHICKNESSXYZ 0 0.1 0.1 0.1"
SHOGUNMGOTHICKNESSXYZ="SHOGUNMGOTHICKNESSXYZ 0 0.1 0.1 0.1"
BEAMPIPEINCLUDE="BEAMPIPEINCLUDE 0"
TARGETHOLDERINCLUDE="TARGETHOLDERINCLUDE 0"
END="END"

FILE="./input/EventBuilder.in"

for arg2 in 500 1000 1500 2000 2500 3000
do

echo ""$INPUTFILE$arg2$FILEEXT1"
"$OUTPUTFILE$1$FILEEXT2$arg2$FILEEXT3"
"$SHOGUNINCLUDE"
"$SHOGUNENERGYRESOLUTION"
"$SHOGUNTIMERESOLUTION"
"$SHOGUNHOUSINGTHICKNESSXYZ"
"$SHOGUNMGOTHICKNESSXYZ"
"$BEAMPIPEINCLUDE"
"$TARGETHOLDERINCLUDE"
"$END" 
" > $FILE

time EventBuilder run_nothing.mac
done
exit 0
