#!/bin/bash
ln -sf EventBuilder.in.dummy ./input/EventBuilder.in

INPUTFILE="INPUTFILE ../SimulationResults/Generator/Efficiency/"
FILEEXT1="MeV"
FILEEXT2="keV.root"
FILEEXT3="keV_beampipe_1mm_pb_6p_res.root"
OUTPUTFILE="OUTPUTFILE ../SimulationResults/Builder/Dali2/Efficiency/"
DALI2INCLUDE="DALI2INCLUDE 1"
DALI2FIINCLUDE="DALI2FIINCLUDE 1"
DALIINDIVIDUAL="DALI2ENERGYRESOLUTIONINDIVIDUAL 0"
#DALI2ENERGYRESOLUTION="DALI2ENERGYRESOLUTION 2 0 0.5"
DALI2ENERGYRESOLUTION="DALI2ENERGYRESOLUTION 2 2.191 0.5"
POSDETECTORONTARGETRESOLUTION="POSDETECTORONTARGETRESOLUTION .3"
ENERGYDETECTORAFTERTARGETINCLUDE="ENERGYDETECTORAFTERTARGETINCLUDE 0"
POSDETECTORAFTERTARGETDISTANCE="POSDETECTORAFTERTARGETDISTANCE 100."
POSDETECTORAFTERTARGETRESOLUTION="POSDETECTORAFTERTARGETRESOLUTION .3"
BETARESOLUTION="BETARESOLUTION 0.001"
BEAMPIPEINCLUDE="BEAMPIPEINCLUDE 1 7.0 7.5"
TARGETHOLDERINCLUDE="TARGETHOLDERINCLUDE 0"
SHIELD="SHIELD 7.5 0.1 0"
END="END" 

FILE="./input/EventBuilder.in"

for arg1 in 100 150 200 250 
do
for arg2 in 250 500 750 1000 1250 1500 1750 2000 2250 2500 2750 3000
do

echo ""$INPUTFILE$arg1$FILEEXT1$arg2$FILEEXT2"
"$OUTPUTFILE$arg1$FILEEXT1$arg2$FILEEXT3"
"$DALI2INCLUDE"
"$DALI2FIINCLUDE"
"$DALI2ENERGYRESOLUTION"
"$DALIINDIVIDUAL"
"$POSDETECTORONTARGETRESOLUTION"
"$ENERGYDETECTORAFTERTARGETINCLUDE"
"$POSDETECTORAFTERTARGETDISTANCE"
"$POSDETECTORAFTERTARGETRESOLUTION"
"$BETARESOLUTION"
"$BEAMPIPEINCLUDE"
"$TARGETHOLDERINCLUDE"
"$SHIELD"
"$END" 
" > $FILE

time EventBuilder run_nothing.mac
done
done

exit 0
