#!/bin/bash

BEAMISOTOPE="BEAMISOTOPE 37 20 20"
BEAMENERGY="BEAMENERGY 195.7 6.063"
BEAMPOSITION="BEAMPOSITION 0.0 2.35 0.0 2.16"
BEAMANGLE="BEAMANGLE 0.0 0.658 0.0 360.0"
TARGET="TARGET 2 7.0 7.0 700"
TARGETANGULARBROADENING="TARGETANGULARBROADENING 1 1.563"
MASSCHANGE="MASSCHANGE 3 3"
BORREL="BORREL 1 8."
GOLDHABER="GOLDHABER 1 90."
GAMMAINPUT="GAMMAINPUT ./input/34Cl.in"
THETARANGE="THETARANGE 0.0 180.0"
NUMBEROFEVENTS="NUMBEROFEVENTS 1000000"
DEFAULTCUTVALUE="DEFAULTCUTVALUE 0.01"
OUTPUTFILE1="OUTPUTFILE ../SimulationResults/Generator/LifetimePaper/34Cl/34cl461kev"
OUTPUTFILE2="ps.root"
DEDXTABLE="DEDXTABLE 1 ./dEdXTables/CaOnBe.in ./dEdXTables/ClOnBe.in"
END="END"


FILE="./input/EventGenerator.in"
FILE2="./input/34Cl.in"
LIMIT=20

rm ./input/EventGenerator.in

for ((arg1=0; arg1 <= LIMIT ; arg1++))
do
echo "LEVEL 0   0.    0.  0.
LEVEL 1 100. 461.0 $arg1
DECAY 1 0 100.
END
" > $FILE2

echo ""$BEAMISOTOPE"
"$BEAMENERGY"
"$BEAMPOSITION"
"$BEAMANGLE"
"$TARGET"
"$TARGETANGULARBROADENING"
"$MASSCHANGE"
"$BORREL"
"$GOLDHABER"
"$GAMMAINPUT"
"$THETARANGE"
"$NUMBEROFEVENTS"
"$DEFAULTCUTVALUE"
"$OUTPUTFILE1$arg1$OUTPUTFILE2"
"$DEDXTABLE"
"$END" 
" > $FILE

time EventGenerator run_nothing.mac
done

exit 0
