#!/bin/bash

BEAMISOTOPE="BEAMISOTOPE 32 10 10"
BEAMENERGY="BEAMENERGY 240.9 26.32"  
BEAMPOSITION="BEAMPOSITION -0.118 1.17 -0.1 1.57"
BEAMANGLE="BEAMANGLE 0.0 0.0 0.0 360.0"
TARGET="TARGET 3 7.0 7.0 2540"  
TARGETANGULARBROADENING="TARGETANGULARBROADENING 0 0.00"
MASSCHANGE="MASSCHANGE 0 0"
BORREL="BORREL 0 8."
GOLDHABER="GOLDHABER 0 90."
GAMMAINPUT="GAMMAINPUT ./input/32ne.in"
THETARANGE="THETARANGE 0.0 180.0"
NUMBEROFEVENTS="NUMBEROFEVENTS 500000"
DEFAULTCUTVALUE="DEFAULTCUTVALUE 0.01"
OUTPUTFILE1="OUTPUTFILE ../SimulationResults/Generator/32ne/32ne_32ne_241mev_715kev_"
OUTPUTFILE2="ps.root"
DEDXTABLE="DEDXTABLE 1 ./dEdXTables/NeOnC.in ./dEdXTables/NeOnC.in"
END="END"


FILE="./input/EventGenerator.in"
FILE2="./input/32ne.in"

for arg1 in 33
do
echo "LEVEL 0   0.    0.  0.
LEVEL 1 100. 715.  $arg1.
DECAY 1 0 100.
END
" > $FILE2

echo ""$BEAMISOTOPE"
"$BEAMENERGY"
"$BEAMPOSITION"
"$BEAMANGLE"
"$TARGET"
"$TARGETANGULARBROADENING"
"$MASSCHANGE"
"$BORREL"
"$GOLDHABER"
"$GAMMAINPUT"
"$THETARANGE"
"$NUMBEROFEVENTS"
"$DEFAULTCUTVALUE"
"$OUTPUTFILE1$arg1$OUTPUTFILE2"
"$DEDXTABLE"
"$END" 
" > $FILE

time EventGenerator run_nothing.mac
done
exit 0
