#!/bin/bash

BEAMISOTOPE="BEAMISOTOPE 33 11 11"
BEAMENERGY="BEAMENERGY 260.0 4.58"  
BEAMPOSITION="BEAMPOSITION -0.231 1.17 -0.18 1.60"
BEAMANGLE="BEAMANGLE 0.0 0.0 0.0 360.0"
TARGET="TARGET 3 7.0 7.0 2540"  
TARGETANGULARBROADENING="TARGETANGULARBROADENING 0 0.00"
MASSCHANGE="MASSCHANGE 1 1"
BORREL="BORREL 1 8."
GOLDHABER="GOLDHABER 1 90."
GAMMAINPUT="GAMMAINPUT ./input/32ne.in"
THETARANGE="THETARANGE 0.0 180.0"
NUMBEROFEVENTS="NUMBEROFEVENTS 500000"
DEFAULTCUTVALUE="DEFAULTCUTVALUE 0.01"
OUTPUTFILE1="OUTPUTFILE ../SimulationResults/Generator/32ne/33na_32ne_260mev_715kev_"
OUTPUTFILE2="ps.root"
DEDXTABLE="DEDXTABLE 1 ./dEdXTables/NaOnC.in ./dEdXTables/NeOnC.in"
END="END"


FILE="./input/EventGenerator.in"
FILE2="./input/32ne.in"

for arg1 in 33
do
echo "LEVEL 0   0.    0.  0.
LEVEL 1 100. 715.  $arg1.
DECAY 1 0 100.
END
" > $FILE2

echo ""$BEAMISOTOPE"
"$BEAMENERGY"
"$BEAMPOSITION"
"$BEAMANGLE"
"$TARGET"
"$TARGETANGULARBROADENING"
"$MASSCHANGE"
"$BORREL"
"$GOLDHABER"
"$GAMMAINPUT"
"$THETARANGE"
"$NUMBEROFEVENTS"
"$DEFAULTCUTVALUE"
"$OUTPUTFILE1$arg1$OUTPUTFILE2"
"$DEDXTABLE"
"$END" 
" > $FILE

time EventGenerator run_nothing.mac
done
exit 0
